### ISSUE TITLE
Need to Remove lines between pages

### ISSUE THREAD

**Issue by Arun10752** [sixcious/infy-scroll#101]
### Description

![Untitled1111](https://github.com/user-attachments/assets/ab034115-b3b4-45f3-aef8-eefb8bd91da7)

Can you remove this line ? thanks

### URL

https://github.com/

### Version

0.8

### Browser

Chromium 109

### OS

Windows 8.1

### Device

PC

### Adherence

- [X] I have read the [Sticky](https://github.com/sixcious/infy-scroll/issues/50) and my issue is directly related to the app and is not related to making it work with a specific website (including [how to make images load](https://github.com/sixcious/infy-scroll/wiki/Missing-Images-or-Blank-Pages))

**Comment by Arun10752** [comment]
Brave Browser

**Comment by sixcious** [comment]
Hi again Arun, I added a new global Style setting in the newest version of Infy Scroll released today on the web stores (Version 8.1).

It's found under OPTIONS > EXTRA. It will let you modify the style of the divider, so you can add CSS like `.infy-scroll-divider { border: none !important; }` to remove the border-top line.

Thanks for making this feature request 💜
