### ISSUE TITLE
Add a Dark Mode Theme

### ISSUE THREAD

**Issue by shawn-yee** [sixcious/infy-scroll#18]
or make "dark reader" extension enable in setting page

**Comment by roysix** [comment]
Hi, thanks for opening this issue!

This one has been on my TODO List for some time. Unfortunately, the Material Design UI Infy is using doesn't currently offer a Dark Mode, and I really don't want to have to implement this on my own via complex CSS/Sass overrides, so I've elected to wait until the Google/Material team adds support for this (for now at least!).

Here's the issue that tracks this:
https://github.com/material-components/material-components-web/issues/5253

We can keep this issue open until it gets implemented. Thanks again.

**Comment by sixcious** [comment]
Hi, I've designed acustom Dark Material theme and it's now in Version 8.

Thanks for opening this issue! 💜
