### ISSUE TITLE
[Feature Request] Custom rules import and add support css

### ISSUE THREAD

**Issue by hoothin** [sixcious/infy-scroll#20]
It would be nice to allow user import custom AutoPagerize rule from urls, I means not only the wedata.
And custom css to fixed sites like 'javascript-hide' on https://yande.re/ is necessary for me.

**Comment by hoothin** [comment]
Also can you add i18n support for other lang then ? Thank you.

**Comment by sixcious** [comment]
Hi hoothin, thanks for using Infy and for this feature request! Those are some great ideas.

I've been wanting to add support for custom CSS for a long time, but I'm just a little worried about Chrome's Manifest V3 not allowing it in the same vein that they won't allow custom JavaScript. I might just put it in the next release and see what happens. It's already been implemented in my development copy [here on GitHub](https://github.com/sixcious/infy-scroll/blob/main/src/base/js/scroll.js#L789-L795).

[Infy's already set up for i18n](https://github.com/sixcious/infy-scroll/blob/main/src/base/_locales/en/messages.json), but I'm still adding and modifying way too many messages in English as it is. Maybe one day when it gets out of beta!

As for importing custom AP rules, it's a great idea. I guess though, I would rather people who already have such custom rules to continue to use their AP extensions and to only use Infy for any other URLs they may need. But if this is something more people want, I'll definitely consider it.

Thanks so much.

**Comment by hoothin** [comment]
Thank you for reply, I wait for your next version.

**Comment by hoothin** [comment]
By the way ,I can help to translate to chinese and spread your great work when i18n ready if you wish. Thanks again.

**Comment by sixcious** [comment]
Thank you very much. I just wanted to let you know that Version 0.7 now has preliminary support for Custom Databases in the Options Database section. It probably isn't as nice as editing in a code editor, but it's a start.

I couldn't add the Custom CSS feature sadly because it's considered remote code. But I did add a custom script for yande.re that deals with the javascript-hide that you may find helpful.

Thanks again for your great suggestions!

**Comment by hoothin** [comment]
That's great! Wish infy-scroll to be better and better!
