### ISSUE TITLE
JS event after loading a new page

### ISSUE THREAD

**Issue by alimuzzaman** [sixcious/infy-scroll#32]
**Feature request**
JS event after loading a new page.
I want to replace/remove some content/char from the page. it would be great if I can subscribe to a event and do modification.
Or can add a class on the div.

**Comment by sixcious** [comment]
Hi,

Thanks for opening this issue.

Writing custom scripts and styles via Custom Events is covered in the [Help Guide](https://github.com/sixcious/infy-scroll/wiki/Scripts-and-Styles). There are examples with code that show you how to do this in a variety of ways.

I'm going to go ahead and close this, but feel free to reply if you still have issues.
