### ISSUE TITLE
Does this extension suports whitelisting?

### ISSUE THREAD

**Issue by alexolog** [sixcious/infy-scroll#33]
I have used several autopager extensions/scripts and the problem with most of them is that they use a "blacklist" model.  That is, they are on by default and allow opting-out for specific sites.

The problem with that approach is that the autopaging code tends to break some sites, sometimes silently, and it is usually the ones where breakage causes the most unfortunate consequences: financial sites, job interview sites, medical/insurance, etc.

Unfortunately, it is impossible to know in advance if a web site will break with autopaging, so the safest approach is the opposite one - a "whitelist" (aka "opt-in") , where the default is not to try to autopage unless the user marks the site as "safe".

Does Infy support this?

**Comment by alexolog** [comment]
Apparently it does

**Comment by sixcious** [comment]
Hi Alex,

Right, technically Infy does suport a Whitelist mode. This is controlled by unchecking the `Auto-activate on all Database URLs` checkbox in the Options. However, the actual ability to whitelist URLs is a little cumbersome as you currently need to manually type in each of the Whitelisted URLs/domains in the Options screen. The next version will fix this by having a 1-Click Blacklist/Whitelist button in the actual Popup's UI, so it will auto-add the URL (its domain) to your Blacklist/Whitelist and stop/start itself in one button click.

I hope this helps answer your question.

**Comment by alexolog** [comment]
Actually, blacklisting the generic rules helped a lot, so effectively it should be working like this:
* All (non-generic) DB rules are whitelisted by default
* Sites not in the DB are whitelisted manually by adding rules.

It would be even more flexible if there was an option to whitelist/blacklist sites that match DB rules, and it seems that there is something like this happening, but it is not configurable and does not work as expected (see issue #35)

Ideally, there would be 2 modes:
1. DB rules activated by default - a URL can be blacklisted
2. DB rules not activated by default - the icon will indicate that there are DB rule(s) matching the URL and will allow the user to whitelist it.

Thank you!
