### ISSUE TITLE
Request: Allow editing saved URLs from the "My Saved URLs" page

### ISSUE THREAD

**Issue by alexolog** [sixcious/infy-scroll#37]
**Feature request**
Please add the option to edit the saved URLs to the the "My Saved URLs" page.  It is more convenient than going through a page that matches the pattern, especially if the page matches more than one pattern.

Can be done with a little "pencil" icon that will open the existing rule configuration dialog with the URL/pattern data pre-loaded.

Thank you!

**Comment by alexolog** [comment]
Also, a "duplicate and edit" or "edit a copy" would be nice.

**Comment by sixcious** [comment]
Hi again Alex,

Thanks for the feature request. Yes, editing Saved URLs in the Options is already planned for the next version update. I don't plan on adding a duplicate feature though. If you really need to duplicate saves, I feel like you could just use the Backup feature to export it to a text editor and copy/paste and then restore/import the text when done.

**Comment by sixcious** [comment]
OK, I've added an Edit Save function in the Options in Version 8. I also added an Add Save button that lets you add a save using a default template or by using an existing save as a template if you check that save before clicking the button.

Thanks for this feature request! 💜
