### ISSUE TITLE
Questions about rules, saved URLs and custom DB

### ISSUE THREAD

**Issue by alexolog** [sixcious/infy-scroll#38]
I have some questions that I think should be addressed in the documentation.

* Where are the new elements inserted in the Element mode?

* What happens if a page matches several rule patterns?
Which of the Saved URLs, DB, and Custom DB take precedence?
What is several patterns in the same category (above) match?  Does Infy Scroll try them sequentially until it finds one that works?  In that case, does order matter (if it does, consider it to be a request to allow reordering of Saved URLs)

* It seems that the custom DB and the Saved URLs address similar needs (user-defined rules).
Are there any differences between them that would suggest using one over the other?
Are there plans to merge them in the future?

Thank you!

**Comment by sixcious** [comment]
Hi again Alex,

Thanks for the great suggestions/questions! I've added some new pages and sections in the wiki/Help Guide to help address your questions below.

- https://github.com/sixcious/infy-scroll/wiki/Append-Modes#insertion-point
- https://github.com/sixcious/infy-scroll/wiki/Activation-and-Prioritization

Lastly, yes, as you know by now, I've merged the Custom Database into the Saves, to avoid repetition/confusion.

The second link should also hopefully answer your follow-up question in #58 about the difference between how databases and saves are prioritized.

I'll go ahead and close this but let me know if you still need more clarification.

Thanks!
