### ISSUE TITLE
Whitelist?

### ISSUE THREAD

**Issue by FCrane** [sixcious/infy-scroll#43]
Hi! 

Great extension - congratulations!!! What I'm really missing is a whitelist, though! I just need the functionality on a few websites, on most others I prefer the regular page separation. So it would be really great to have a whitelist where I can enter just the pages I want Infy-Scroll to handle! 

Like e.g.:
https://www.google.*

etc.

Thanks!

**Comment by sixcious** [comment]
Hi, thanks for opening this issue!

A whitelist option is already included in Infy Scroll. Just head to the Options screen, and inside the Database section, uncheck the Auto-activate checkbox. The Help Guide has a full section on this:
https://github.com/sixcious/infy-scroll/wiki/Database#the-most-important-database-setting

If that helps, let me know so this issue can be closed.

Thanks!

**Comment by FCrane** [comment]
Hi!

Thanks - great, I didn't find that option when going over all setting pages. Maybe you can add "(turn off to use a whitelist)" to the auto-activate checkbox to make the whitliste easier to find...

But it's great that your extension already supports it!!

Once more thank you for the great extension - it is by far the best of all auto-pagers out there! Unfortunately, it does not show up if you search for "auto pager", "autopagerize", "infinity scroll", etc. when you search in the Firefox Add-Ons, so I just found it by accident (somebody mentioned it in a review of another extension, I think). Maybe you can add some keywords or tags so that it is easier to find?

Thanks!
