### ISSUE TITLE
Images spill over text on fetched pages (Not executing scripts on appended pages)

### ISSUE THREAD

**Issue by alexolog** [sixcious/infy-scroll#45]
**Describe the bug**  
On some forums, images are not resized correctly on fetched pages, and they spill over the text.
See screenshots below.

**Website**  
https://forums.redflagdeals.com/fido-bf-special-phone-plan-20gb-lte-30-m-first-line-then-25-m-second-line-2581484/

**Environment**  
 - Device: Desktop
 - OS: Win 10
 - Browser: Firefox
 - Browser Version: 108.0b5 64-bit (but happened on earlier versions as well)
 - Extension Version: 0.7

**Screenshots (Optional)**  

Actual:
![image](https://user-images.githubusercontent.com/2112513/204024930-76e018df-b8d1-485b-ad9a-77636a7904d5.png)

Expected:
![image](https://user-images.githubusercontent.com/2112513/204025451-ac4f4d39-46ae-419c-8ffd-d8dc7e51da5d.png)

**Comment by sixcious** [comment]
Hi Alex,

Thanks for opening another issue.

That specific website uses its own script to resize its images to thumbnail size. There isn't really anything Infy is doing wrong here; it's appending the images in the original state that the website delivers them, but it can't make the website execute its script again to resize them. However, I'll provide you with a couple of solutions:

1. If you use the Iframe/Element Iframe append modes, it will append that site's scripts again, which will resize the images to their thumbnail size.
2. You could also try writing your own [custom script](https://github.com/sixcious/infy-scroll/wiki/Scripts-and-Styles) if you'd rather not deal with iframes. The website looks like it's just doing a simple swap of the image's src attributes with a modification to the width/height in the filename pattern.

**Comment by alexolog** [comment]
Thank you, Element Iframe sort of works.
