### ISSUE TITLE
Version 0.8 Testing & Feedback

### ISSUE THREAD

**Issue by sixcious** [sixcious/infy-scroll#48]
Hi everyone,

I'm currently working on the next version of Infy, Version 0.8. This is going to be a pretty big update. If anyone would like to help test this version before it's released, please watch or subscribe to this issue. I'll update the repository and this post with instructions when it's ready.

Thank you!

**Comment by sixcious** [comment]
Hi again,

I've uploaded a pre-release of Version 0.8 on GitHub. Here are instructions on how to install it and the version notes:
- [Installing](https://github.com/sixcious/infy-scroll#installing)
- [Version Notes](https://github.com/sixcious/infy-scroll/blob/main/docs/VERSION.md)

There's a ton of changes, but the biggest new features in this release are the new AJAX append mode and the SPA option. I'll be adding more details about these in the README.

If you are on Version 0.7 (the latest version on the web stores), you can Backup your data to a file and then Restore it in 0.8 via the Backup/Restore feature in the Options. This will help test to see if your saves still work, and if everything got updated correctly. This is the part I need the most help with testing because I refactored a lot of the save data.

If you find any issues or have any feedback, please comment and let me know. 

Thank you again!

**Comment by sixcious** [comment]
Happy Holidays and Happy New Year!

I've uploaded a newer version here on GitHub that has some major UI improvements I hope everyone will like. I designed a custom made dark theme in Material (Addresses #18), which I think looks really cool! Also, all path inputs have now been changed to resizable textareas and are using Roboto Mono (monospace) font for better readability (Addresses #10). I think this is going to be a major improvement. I tried to fix or address every single issue opened in 2022 with this release, so I'm real hopeful it will be well received.

Thank you again!

**Comment by Dook1** [comment]
Maybe it makes sense to release already or there are some problems?

**Comment by sixcious** [comment]
Thank you Dook for the comment (and for the review!). 💜 

I'm hopeful to release 0.8 to the web stores soon. I was hoping for March, but it looks like April is my new goal. It's basically done; there's still a few property names left to rename and finalize and some more AJAX/SPA testing I need to do. 0.8 is also pretty much a complete rewrite and is the biggest and hardest update I've ever had to develop, so I'm trying to make sure it's a smooth update for all the web store users. So hopefully it'll be soon!

**Comment by Dook1** [comment]
Okay, I'm looking forward to it.

**Comment by alexolog** [comment]
Is there a summary of changes?

**Comment by sixcious** [comment]
Hi Alex,

This is a [full list](https://github.com/sixcious/infy-scroll/wiki/Version-History) of all the changes and this is a [short summary](https://github.com/sixcious/infy-scroll/blob/dfdcac61133facb1266251c21ee923386063965e/src/base/_locales/en/messages.json#L14-L23) of the most important ones.

Thank you!

**Comment by Dook1** [comment]
Thanks

**Comment by sixcious** [comment]
Thank you everyone! 💜
