### ISSUE TITLE
Removing Next Link Property and Insert Before?

### ISSUE THREAD

**Issue by sixcious** [sixcious/infy-scroll#49]
Hi everyone,

I'm looking for feedback on the removal of these two fields. It's these two inputs outlined in red in the UI:

![Infy Scroll UI Removals](https://user-images.githubusercontent.com/1027814/209176781-1b4f6572-0067-4113-b746-d8ec92d34fd5.png)

Right now, this is just about removing them from the UI. They would still be in the Save object, which you will be able to edit in the Options screen. Removing these two fields would allow the Next Link Path and the Page Element Path inputs to have more room and be 100% full width.

**Next Link Property**
I added this because I thought there may have been a use-case for a site secretly storing the next link in a property/attribute besides `href`. However, since releasing Infy, I haven't encountered a website yet that actually does this. Has anyone?

**Insert Before**
There are currently only 50 Database URLs that have an Insert Before path entered for them, and many of them aren't working anymore. Has anyone used this field and would prefer that it remain in the UI?

Thank you for any feedback!

**Comment by alexolog** [comment]
I have never used either, so I would not mind removing them from the UI.
Will it be possible to keep them in the implementation so if a site actually needs either, they can be set via other means?

**Comment by sixcious** [comment]
Thanks Alex for the reply. Yes, that's the plan. They can still be set in the new Options Edit Save dialog if they need to.

Thank you!

**Comment by sixcious** [comment]
Hi,

I added an option in Version 8 to show/hide these "Extra Inputs" in the Options screen for now. It's been almost a month and no one seems to have complained, so I'll leave it like this for the time being.

(One thing I forgot to do is show the Insert Before Path if one exists for the Database URL you're on if you have the option unchecked to not show. I'll add that for the next version maybe.)

Thank you! 💜
