### ISSUE TITLE
LinkedIn

### ISSUE THREAD

**Issue by jason88fr** [sixcious/infy-scroll#52]
### What happened?

I can't seem to get the extension to function on LinkedIn.

### URL

https://www.linkedin.com/search/results/people/?keywords=informatique&origin=SWITCH_SEARCH_VERTICAL&sid=Fpy

### Version

Version 0.7 β

### Browser

Brave Version 1.48.167 Chromium: 110.0.5481.104 (Official Build) (64-bit)

### OS

Windows 11

### Device

PC

**Comment by sixcious** [comment]
Hi Jason!

That's an AJAX/SPA site, so you'll need to use Version 0.8's new AJAX append mode to make it work there. Specifically, you'll need the Click Button Action, AJAX append mode, and the SPA Late Activation setting checked in the UI Window.

Version 0.8 is currently only on GitHub as a preview/test. If you'd like to try it, instructions are here:
https://github.com/sixcious/infy-scroll#installation

Let me know if this helps.
