### ISSUE TITLE
Add an option to load all pages without the need to scroll down

### ISSUE THREAD

**Issue by JS-1982** [sixcious/infy-scroll#66]
### Feature Request

It would be great if there was an option to chose to load all following pages, without the requirement to manually scroll down and wait for the following pages to load. Maybe it would be possible to add such option to the menu?

**Comment by sixcious** [comment]
Hi JS,

Thank you for opening this feature request. 💜 This is actually already in Infy. Click on the toolbar icon and enter the UI Window's Setup view (you may need to click the pencil icon if you're in the Buttons view). Then toggle on the orange "AUTO" switch in the lower-left and set it up to your preference and timing schedule and click the "ACCEPT" button.

Let me know if that works for you!

**Comment by Jojin-US** [comment]
Does the Auto feature save itself as "ON" to "My Saves" for specific websites, to all websites or do you have to manually click the Auto button for every new instance?

**Comment by sixcious** [comment]
Hi Jojin, Auto can be a dangerous feature (for example, IP bans or a website detecting "suspicious behavior"), so it's something that needs to be setup and accepted manually each time you want it to run (however, it _does_ remember the last Auto settings you used in the UI Window for convenience). It doesn't seem intuitive for Auto to auto-activate itself each time you visit a saved site if you only intended it to just run the one time you set it. I guess I could add another setting that asks if the user actually wants a saved site to always auto-activate with Auto on, but I'm running out of room left in the UI Window and it's not something I'm 100% sure about including. (I'll keep it in mind for the future though whenever I come back to work on Infy!)

**Comment by Jojin-US** [comment]
That makes sense.  I use it for many list sites like Amazon or discussion threads, where I always end up scrolling the whole list and then use search to find specific information.

With the UI having limited space, it would still be great to have a hotkey to auto load X pages.  It's the one feature which keeps me using the old Autopagerize even though I have to manually define each url.

![pic](https://github.com/sixcious/infy-scroll/assets/76228407/47713343-2e8c-4de5-b3c8-1a2c8f8228b0)

**Comment by sixcious** [comment]
Hi again Jojin, could you open that as a separate issue as a Feature Request so we can move discussion there? I would only add one shortcut key for a feature like that (not four); however it would be implemented in a flexible way that would still let you enter the command multiple times if you wanted it to keep appending more and more pages. I think that's fair.

JS, I'm going to go ahead and close this since your issue/feature seems to already be in Infy, but feel free to reply if you still have any questions!

Thanks. 💜
