### ISSUE TITLE
warn when picking elements from altered DOM

### ISSUE THREAD

**Issue by wang-d** [sixcious/infy-scroll#70]
### Feature Request

This is more a defense against user error than a feature, but would it be hard for Infy Scroll to remember when it has altered the DOM, and show a warning if someone tries to pick elements from the altered DOM?  E.g.,

> Cannot pick elements from page after appending.  Please reload and pick elements from the unaltered page.

Or words to that effect.

In the save URL dialogue for a website, for the element append method, I clicked the ink dropper icon to choose an element to append.  I picked an element, then went back into the save URL dialogue as instructed, only to see that a warning that the CSS selector matched no elements.

Turns out I had already let Infy Scroll append two extra pages using the page method, and the element I picked was from the third page.  So of course it didn't exist in the original document.

It all worked once I reloaded the tab and picked an element from the original page, before Infy Scroll started altering the DOM.

**Comment by sixcious** [comment]
Hi again, thanks for making this feature request!

Yes, so the Element Picker (EP) is providing the path to the element based on the visible (main) document you're interacting with. Behind the scenes, in Infy Scroll, when it's reporting whether the Next Link Path works or not, it's actually only checking the latest page's document that was fetched, so the documents are different and the path may not work for both documents.

I've added a note/warning regarding this use-case in the Element Picker Help Guide:
https://github.com/sixcious/infy-scroll/wiki/Element-Picker#multiple-document-contexts-infy-scroll-only

There is practically no room left in the UI, but I'll try and see if I can also add a new snackbar message that shows up in the EP window for the next version of Infy (though, I'm not sure when that will be happening!).

Thank you! 💜

**Comment by wang-d** [comment]
Thanks for the quick response!
