### ISSUE TITLE
On some websites it does not load more than 5 pages

### ISSUE THREAD

**Issue by kaiso77** [sixcious/infy-scroll#87]
### Description

Hi, I have a problem with loading pages on some websites. it does not load more than 5 pages, although there are much more than 5.  What causes this and how to fix it?

### URL

https://www.kleinanzeigen.de/

### Version

ver.08

### Browser

Chrome Version 124.0.6367.209 (64-Bit)

### OS

Windows 11

### Device

PC

### Adherence

- [X] I have read the [Sticky](https://github.com/sixcious/infy-scroll/issues/50) and my issue is directly related with the app and is not related to making it work with a specific website

**Comment by sixcious** [comment]
Hi kaiso77, welcome to GitHub and thanks for opening this issue! 💜 

I can't see anything to infinite scroll on the URL you posted, as it is just the domain and front page of the site. Could you please provide two *full* example URLs (preferably, from at least two different domains) that show this behavior so I can reproduce this? Also please post the settings you are using for each URL; if you are using a Saved URL, please copy and paste the entire JSON object here from `OPTIONS` > `SAVES` (it should begin with `{` and end with `}`). If it's a Database URL, just let me know.
