### ISSUE TITLE
Blacklisting dows not work

### ISSUE THREAD

**Issue by LurkerHub** [sixcious/infy-scroll#90]
### Description

Infi triggers on the URL below, showing a "next url" from the DB, even though I blacklisted those DB entries as follows:
```
(^https?://.*?(forums?(display\\.php\\?)?))
(^https?://.*(showthread\\.php\\?|forum|threads?))
```

The "next link" is shown to be
```
(//link[contains(concat(' ', @rel, ' '), ' next ')][1][@href=//a/@href]
|//a[@rel='next' or .='>' or .='Next ›' or .='Next >' or .='Next']
|(//td[@class='middletext']|//div[starts-with(@class,'pagelinks') or contains(@class,'pagesclass')])/text()[contains(.,']')]/following-sibling::a[@class='navPages'][1]
|(//span|//a)[contains(@class,'current')][number()>0]/following-sibling::a[not(@class='go_page')][1][not(ancestor::*[contains(@style, 'display: none')])]
|//span[contains(@class,'selected')][number()>0]/following-sibling::span[1]/a
|//li[starts-with(@class,'pager-next')]/a
|//div[@class='pages']/text()[number(translate(., '[] ', ''))>0]/following-sibling::a[1][number()>0])[string(@href) and not(starts-with(@href, '#') or starts-with(@href, 'javascript'))]
```

### URL

https://elliquiy.com/forums/index.php?topic=344075.75

### Version

0.8

### Browser

FF 123b09

### OS

Windpows 10

### Device

PC

### Adherence

- [X] I have read the [Sticky](https://github.com/sixcious/infy-scroll/issues/50) and my issue is directly related with the app and is not related to making it work with a specific website

**Comment by sixcious** [comment]
Hi, thanks for opening this issue.💜 

Your blacklisted URLs aren't quite right; it should be (note the `\` characters):
````
(^https?://.*(showthread\.php\?|forum|threads?))
````

Let me know if that works.

**Comment by LurkerHub** [comment]
Interesting, I thought they had to copied from the DB verbatim.
You may want to document it.

**Comment by sixcious** [comment]
Hi again,

You might have copied the Database URL from a JSON String, which will be escaped. If you see a `\` in a String (`"..."`), it will be escaped with an extra backslash. I believe the only place in the app that shows the URLs enclosed in Strings is in the Options screen's Database Items dialog, but this is really a JavaScript language restriction. I can definitely add a note/reminder about this in the Help Guide.

The "non-escaped" Database URL is how it is displayed on Wedata and when hovering over the Database Icon in Infy's Popup:
http://wedata.net/items/65332

<img src="https://github.com/sixcious/infy-scroll/assets/1027814/4d94e441-2415-4e3e-bed4-929ba2539527" width="500">

Thanks for bringing this up. 💜
