### ISSUE TITLE
Images are not loading in the following pages

### ISSUE THREAD

**Issue by nadi-code** [sixcious/infy-scroll#93]
### Description

Hello,

I'm trying to use your extension on this website: https://discords.com/emoji-list/search?term=yay&page=1

While it does scroll to the next page, the photos are not loading. 

I wish to scroll all the way and then use another extension called 'Image Downloader' to download all the emojis (hopefully it is possible). Can you please help me? It would be much appreciated.

Thank you and kind regards,
Nadine

### URL

https://discords.com/emoji-list/search?term=yay&page=1

### Version

Latest

### Browser

Google Chrome (up to date)

### OS

Windows 10 Pro

### Device

PC

### Adherence

- [X] I have read the [Sticky](https://github.com/sixcious/infy-scroll/issues/50) and my issue is directly related with the app and is not related to making it work with a specific website

**Comment by sixcious** [comment]
Hi Nadine, thanks for opening this issue💜 

Although this isn't an issue with the app itself, I can try helping you with this specific website as a one-time courtesy.

That's an AJAX site that uses links as a fallback, and it most likely uses scripts to generate the images. You can use an iframe append mode to load the scripts (`Iframe`, `Element Iframe`, or `AJAX Iframe`) and to generate the images. Just note that if you are using the regular `Iframe` append mode, whatever downloader you're going to use needs to work with iframes.

Also, just a heads up, but in case you're using the default keywords to find the next page on that site, the site uses a badly named keyword that actually takes you to the 5th page link. The real path to the next link/click element should look something like the following selector:

```
.page-item.active + li a
```

Let me know if this helps.
