### ISSUE TITLE
Not easy to pause, Show pause/resume as overlay in bottom right of website or near page number

### ISSUE THREAD

**Issue by Arun10752** [sixcious/infy-scroll#94]
### Description

Not easy to pause, Show pause/resume as overlay in bottom right of website or near page number

### URL

https://github.com/

### Version

0.8

### Browser

Chromium 109

### OS

Windows 8.1

### Device

PC

### Adherence

- [X] I have read the [Sticky](https://github.com/sixcious/infy-scroll/issues/50) and my issue is directly related to the app and is not related to making it work with a specific website (including [how to make images load](https://github.com/sixcious/infy-scroll/wiki/Missing-Images-or-Blank-Pages))

**Comment by sixcious** [comment]
Hi again Arun, I added a new Auto Pause/Resume Button option in the newest version of Infy Scroll released today on the web stores (Version 8.1).

Thanks for making this feature request 💜
