### ISSUE TITLE
I would like there to be an option for the position of the Page Overlay.

### ISSUE THREAD

**Issue by dog6o** [sixcious/infy-scroll#95]
### Description

I would like to have an option for the position of the Page Overlay.

As the title says, I would like to have an option for the position of the Page Overlay.
The Page Overlay is fixed to the top right, but currently most websites have a UI that has a header at the top, which interferes with operation.
Personally I would like to move it to the bottom right, but for some reason this is not possible with the custom CSS extensions in "User JavaScript and CSS" or "Stylus", which is causing problems.

My requests can be summarized below.
- Since the position of the Page Overlay is fixed to the top right, I would like to have an option for any of the four corners.
- I would like a text box or slider to be available to select the transparency of the Page Overlay.

### URL

https://dummy

### Version

Version 8 — The Eightfinity Edition

### Browser

Microsoft Edge Version 129.0.2792.52 (Official build) stable app, beta channel (64-bit)

### OS

Windows 11 Pro Insider Preview - Build 27695.1000

### Device

PC

### Adherence

- [X] I have read the [Sticky](https://github.com/sixcious/infy-scroll/issues/50) and my issue is directly related to the app and is not related to making it work with a specific website (including [how to make images load](https://github.com/sixcious/infy-scroll/wiki/Missing-Images-or-Blank-Pages))

**Comment by sixcious** [comment]
Hi dog6o, thank you for making this feature request! 💜 

I published a new version of Infy Scroll this week to the web stores (v8.1) and I added a new move button inside the overlay so it can be moved to whichever corner you'd like it to go to instantly, as each website is different.

I also added a new "Add custom styles" setting under OPTIONS > EXTRA and I also added an example showing you how to change the opacity for you, so you can simply copy and paste it.

Please feel free to let me know if there are any issues.

Thank you again and for your patience! 💜
