### ISSUE TITLE
Prevent duplicate content from being appended

### ISSUE THREAD

**Issue by DandyClubs** [sixcious/infy-scroll#98]
### Description

sometimes 

scroll 3 page view

Part of page 2 is repeated on page 3 when  add 1st page New Item

----page 1
Post 1
Post 2
Post 3
Post 4
Post 5
Post 6
Post 7
Post 8
Post 9
Post 10

---page2

Post 11
Post 12
Post 13
Post 14
Post 15
Post 16
Post 17
Post 18
Post 19
Post 20

---page3

Post 17
Post 18
Post 19
Post 20
Post 21
Post 22
Post 23
Post 24
Post 25
Post 26

is possible get first page new item replace 3page dup item without Reload ?

### URL

ex

### Version

8

### Browser

firefox

### OS

windows 11

### Device

PC

### Adherence

- [X] I have read the [Sticky](https://github.com/sixcious/infy-scroll/issues/50) and my issue is directly related to the app and is not related to making it work with a specific website (including [how to make images load](https://github.com/sixcious/infy-scroll/wiki/Missing-Images-or-Blank-Pages))

**Comment by sixcious** [comment]
Hi again DandyClubs,

Yes, this is something that happens on fast-moving sites where content is being uploaded rapidly. I'll try and see if I can add in a "Prevent duplicate content" option.

Thank you for the suggestion! 💜

**Comment by sixcious** [comment]
Hi again DandyClubs, I published a new version of Infy Scroll this week on the web stores (v8.1) and added a new `Prevent duplicate content` option in the Popup Window's Scripts and Styles dialog. If you check it and then select the `Individual Elements` option, it should do what you are asking for.

Please let me know if you experience any issues.

Thanks for your patience and for making this feature request 💜
