### ISSUE TITLE
cha't change button icon color 

### ISSUE THREAD

**Issue by DandyClubs** [sixcious/infy-scroll#99]
### Description

![9e1659b05ff91fc867b96ea7dfe98e81](https://github.com/user-attachments/assets/25138be8-039e-4e40-8b9b-19e6961d3fa3)

Icon readability is not good on some sites.

try  add style

div.infy-scroll-divider svg path {
	fill: #FFF !important;
}

but  It does not work because !important has already been applied.

<path style="fill: #55555F !important;" d="M352 352c-8.188 0-16.38-3.125-22.62-9.375L192 205.3l-137.4 137.4c-12.5 12.5-32.75 12.5-45.25 0s-12.5-32.75 0-45.25l160-160c12.5-12.5 32.75-12.5 45.25 0l160 160c12.5 12.5 12.5 32.75 0 45.25C368.4 348.9 360.2 352 352 352z"></path>

### URL

test

### Version

8

### Browser

firefox

### OS

windows 11

### Device

PC

### Adherence

- [X] I have read the [Sticky](https://github.com/sixcious/infy-scroll/issues/50) and my issue is directly related to the app and is not related to making it work with a specific website (including [how to make images load](https://github.com/sixcious/infy-scroll/wiki/Missing-Images-or-Blank-Pages))

**Comment by sixcious** [comment]
Hi once again DandyClubs!

Try saving the URL and then adding `"color": "#FFF"` to the [JSON Save object](https://github.com/sixcious/infy-scroll/wiki/Saves#scroll-options) (OPTIONS > SAVES). That will allow you to change the page divider color completely, including the SVG fill color.

Please let me know if that works 💜
